import type { Metadata } from "next";
import {Nunito} from "next/font/google";
import "./globals.css";
import "./responsive.css";
import {Header} from "@/components/Header";
import {Footer} from "@/components/Footer";


const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight:["300", "700"]
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${nunito.variable} antialiased`}
    >

      <body>

        <div className="site">

          <Header />

          {children}

        </div>{/* site */}  

        <Footer />
      
      </body>
    </html>
  );
}
